### ISSUE TITLE
Akamai-ULS Stops Sending Messages to Splunk Due to HTTP Aggregation Queue Being Full

### ISSUE THREAD

**Issue by sethumadhav07** [akamai/uls#77]
**Description**:  
I am encountering an issue with the Akamai-ULS app, where, in some cases, it stops sending eaa access log messages to Splunk because it gets stuck for an unknown reason. This issue seems to be related to the HTTP Aggregation queue getting full and not clearing up. As a result, no messages are being sent to Splunk for extended periods.

**Observed Behavior**:  
- The following messages appear repeatedly in the logs for various eaa access log messages:  
  ```
  UlsOutput Trying to send data via HTTP
  UlsOutput HTTP Aggregation queue is already full - not adding any more entries. Size: (1/1)
  MSG[29349] Delivery (output) attempt 1 of 10
  ULS was not able to deliver the log message after 10 attempts - (continuing anyway as my config says)
  ```
- This pattern is repeated for many access log messages over several hours, during which none of the messages are being sent to Splunk.
- The issue only appears after the pod has been running for a few days without any problems. After an undefined period, the above messages begin to appear, and messages stop being delivered.

**Configuration**:  
Below is the relevant configuration:

```yaml
akamai_uls:
  eaa_access:
    environment:
      ULS_LOGLEVEL: "DEBUG"
      ULS_INPUT: "EAA"
      ULS_FEED: "ACCESS"
      ULS_OUTPUT: "HTTP"
      ULS_HTTP_AGGREGATE: 1
      ULS_EDGERC: /opt/akamai-uls/.edgerc
      ULS_DEBUGLOGLINES: "True"
      ULS_AUTORESUME: "True"
      ULS_NOCALLHOME: "True"
      ULS_HTTP_INSECURE: "True"
      NO_PROXY: "localhost,127.0.0.1,::1"
      REQUESTS_CA_BUNDLE: /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
```

**Expected Behavior**:  
- The HTTP Aggregation queue should not get stuck. EAA access log messages should be consistently delivered to Splunk without repeated failures.
- If there is a failure in delivering eaa access log messages, the error message should provide a reason for the failure, so it's easier to troubleshoot.

**Request for Assistance**:  
1. Has anyone else observed this issue?
2. Is there a known solution or workaround?
3. Can you suggest a way to get more detailed error messages in the logs, so it’s clear why HTTP sends are failing?

**Additional Information**:  
It’s unclear why the HTTP sends fail, as the error message does not indicate the specific reason. It would be beneficial if a more detailed error message could be logged, providing insights into the failure reason.

---

**ULS Version**  
1.8.3
